<?php

namespace Database\Seeders;

use App\Models\Menu;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $menus = [
            // Makanan Pembuka (Category 1)
            [
                'category_id' => 1,
                'name' => 'Gado-Gado Jakarta',
                'description' => 'Sayuran segar dengan bumbu kacang khas Jakarta, dilengkapi lontong dan kerupuk',
                'price' => 35000,
                'image' => 'https://via.placeholder.com/400x300?text=Gado-Gado',
                'is_vegetarian' => true,
                'is_spicy' => false,
                'spicy_level' => null,
                'is_available' => true,
                'view_count' => rand(50, 200),
                'sort_order' => 1,
            ],
            [
                'category_id' => 1,
                'name' => 'Lumpia Semarang',
                'description' => 'Lumpia basah khas Semarang dengan isian rebung, telur, dan udang',
                'price' => 25000,
                'image' => 'https://via.placeholder.com/400x300?text=Lumpia',
                'is_vegetarian' => false,
                'is_spicy' => false,
                'spicy_level' => null,
                'is_available' => true,
                'view_count' => rand(50, 200),
                'sort_order' => 2,
            ],
            [
                'category_id' => 1,
                'name' => 'Tahu Gejrot',
                'description' => 'Tahu goreng dengan kuah pedas manis asam yang menyegarkan',
                'price' => 20000,
                'image' => 'https://via.placeholder.com/400x300?text=Tahu+Gejrot',
                'is_vegetarian' => true,
                'is_spicy' => true,
                'spicy_level' => 'medium',
                'is_available' => true,
                'view_count' => rand(50, 200),
                'sort_order' => 3,
            ],
            [
                'category_id' => 1,
                'name' => 'Perkedel Jagung',
                'description' => 'Perkedel jagung manis renyah dengan taburan daun bawang',
                'price' => 18000,
                'image' => 'https://via.placeholder.com/400x300?text=Perkedel+Jagung',
                'is_vegetarian' => true,
                'is_spicy' => false,
                'spicy_level' => null,
                'is_available' => true,
                'view_count' => rand(50, 200),
                'sort_order' => 4,
            ],
            [
                'category_id' => 1,
                'name' => 'Sate Lilit Bali',
                'description' => 'Sate ikan cincang dengan bumbu khas Bali, dipanggang sempurna',
                'price' => 40000,
                'image' => 'https://via.placeholder.com/400x300?text=Sate+Lilit',
                'is_vegetarian' => false,
                'is_spicy' => false,
                'spicy_level' => null,
                'is_available' => true,
                'view_count' => rand(50, 200),
                'sort_order' => 5,
            ],

            // Makanan Utama (Category 2)
            [
                'category_id' => 2,
                'name' => 'Nasi Goreng Kambing',
                'description' => 'Nasi goreng dengan potongan daging kambing empuk, telur mata sapi, dan acar',
                'price' => 55000,
                'image' => 'https://via.placeholder.com/400x300?text=Nasi+Goreng+Kambing',
                'is_vegetarian' => false,
                'is_spicy' => true,
                'spicy_level' => 'medium',
                'is_available' => true,
                'view_count' => rand(100, 300),
                'sort_order' => 1,
            ],
            [
                'category_id' => 2,
                'name' => 'Soto Ayam Lamongan',
                'description' => 'Kuah soto kuning gurih dengan ayam kampung, koya, dan krupuk',
                'price' => 45000,
                'image' => 'https://via.placeholder.com/400x300?text=Soto+Ayam',
                'is_vegetarian' => false,
                'is_spicy' => false,
                'spicy_level' => null,
                'is_available' => true,
                'view_count' => rand(100, 300),
                'sort_order' => 2,
            ],
            [
                'category_id' => 2,
                'name' => 'Rendang Padang',
                'description' => 'Daging sapi rendang empuk dengan bumbu rempah khas Minang yang kaya rasa',
                'price' => 75000,
                'image' => 'https://via.placeholder.com/400x300?text=Rendang',
                'is_vegetarian' => false,
                'is_spicy' => true,
                'spicy_level' => 'hot',
                'is_available' => true,
                'view_count' => rand(100, 300),
                'sort_order' => 3,
            ],
            [
                'category_id' => 2,
                'name' => 'Ayam Bakar Taliwang',
                'description' => 'Ayam bakar khas Lombok dengan sambal plecing yang pedas nikmat',
                'price' => 65000,
                'image' => 'https://via.placeholder.com/400x300?text=Ayam+Taliwang',
                'is_vegetarian' => false,
                'is_spicy' => true,
                'spicy_level' => 'extra_hot',
                'is_available' => true,
                'view_count' => rand(100, 300),
                'sort_order' => 4,
            ],
            [
                'category_id' => 2,
                'name' => 'Ikan Bakar Jimbaran',
                'description' => 'Ikan kakap segar dipanggang dengan bumbu rica-rica khas Bali',
                'price' => 85000,
                'image' => 'https://via.placeholder.com/400x300?text=Ikan+Bakar',
                'is_vegetarian' => false,
                'is_spicy' => true,
                'spicy_level' => 'mild',
                'is_available' => true,
                'view_count' => rand(100, 300),
                'sort_order' => 5,
            ],
            [
                'category_id' => 2,
                'name' => 'Rawon Setan',
                'description' => 'Sup daging sapi hitam khas Surabaya dengan kluwek yang khas',
                'price' => 50000,
                'image' => 'https://via.placeholder.com/400x300?text=Rawon',
                'is_vegetarian' => false,
                'is_spicy' => false,
                'spicy_level' => null,
                'is_available' => true,
                'view_count' => rand(100, 300),
                'sort_order' => 6,
            ],
            [
                'category_id' => 2,
                'name' => 'Gulai Kepala Ikan',
                'description' => 'Kepala ikan kakap dalam kuah gulai kuning yang gurih',
                'price' => 70000,
                'image' => 'https://via.placeholder.com/400x300?text=Gulai+Kepala+Ikan',
                'is_vegetarian' => false,
                'is_spicy' => false,
                'spicy_level' => null,
                'is_available' => true,
                'view_count' => rand(100, 300),
                'sort_order' => 7,
            ],
            [
                'category_id' => 2,
                'name' => 'Nasi Liwet Solo',
                'description' => 'Nasi gurih dengan opor ayam, areh, telur pindang, dan lalapan',
                'price' => 48000,
                'image' => 'https://via.placeholder.com/400x300?text=Nasi+Liwet',
                'is_vegetarian' => false,
                'is_spicy' => false,
                'spicy_level' => null,
                'is_available' => true,
                'view_count' => rand(100, 300),
                'sort_order' => 8,
            ],
            [
                'category_id' => 2,
                'name' => 'Pepes Ikan Mas',
                'description' => 'Ikan mas segar dibumbui rempah, dibungkus daun pisang dan dikukus',
                'price' => 60000,
                'image' => 'https://via.placeholder.com/400x300?text=Pepes+Ikan',
                'is_vegetarian' => false,
                'is_spicy' => false,
                'spicy_level' => null,
                'is_available' => true,
                'view_count' => rand(100, 300),
                'sort_order' => 9,
            ],
            [
                'category_id' => 2,
                'name' => 'Cap Cay Seafood',
                'description' => 'Tumisan sayuran segar dengan aneka seafood dalam saus tiram',
                'price' => 58000,
                'image' => 'https://via.placeholder.com/400x300?text=Cap+Cay',
                'is_vegetarian' => false,
                'is_spicy' => false,
                'spicy_level' => null,
                'is_available' => true,
                'view_count' => rand(100, 300),
                'sort_order' => 10,
            ],

            // Minuman (Category 3)
            [
                'category_id' => 3,
                'name' => 'Es Cendol Durian',
                'description' => 'Es cendol dengan topping durian segar, santan, dan gula merah',
                'price' => 28000,
                'image' => 'https://via.placeholder.com/400x300?text=Es+Cendol',
                'is_vegetarian' => true,
                'is_spicy' => false,
                'spicy_level' => null,
                'is_available' => true,
                'view_count' => rand(50, 150),
                'sort_order' => 1,
            ],
            [
                'category_id' => 3,
                'name' => 'Es Kelapa Muda',
                'description' => 'Kelapa muda segar dengan sirup dan es serut',
                'price' => 22000,
                'image' => 'https://via.placeholder.com/400x300?text=Es+Kelapa',
                'is_vegetarian' => true,
                'is_spicy' => false,
                'spicy_level' => null,
                'is_available' => true,
                'view_count' => rand(50, 150),
                'sort_order' => 2,
            ],
            [
                'category_id' => 3,
                'name' => 'Jus Alpukat',
                'description' => 'Jus alpukat segar dengan susu dan cokelat',
                'price' => 25000,
                'image' => 'https://via.placeholder.com/400x300?text=Jus+Alpukat',
                'is_vegetarian' => true,
                'is_spicy' => false,
                'spicy_level' => null,
                'is_available' => true,
                'view_count' => rand(50, 150),
                'sort_order' => 3,
            ],
            [
                'category_id' => 3,
                'name' => 'Wedang Uwuh',
                'description' => 'Minuman rempah tradisional hangat khas Yogyakarta',
                'price' => 18000,
                'image' => 'https://via.placeholder.com/400x300?text=Wedang+Uwuh',
                'is_vegetarian' => true,
                'is_spicy' => false,
                'spicy_level' => null,
                'is_available' => true,
                'view_count' => rand(50, 150),
                'sort_order' => 4,
            ],
            [
                'category_id' => 3,
                'name' => 'Teh Telur',
                'description' => 'Teh hangat dengan telur ayam kampung yang dikocok khas Medan',
                'price' => 20000,
                'image' => 'https://via.placeholder.com/400x300?text=Teh+Telur',
                'is_vegetarian' => true,
                'is_spicy' => false,
                'spicy_level' => null,
                'is_available' => true,
                'view_count' => rand(50, 150),
                'sort_order' => 5,
            ],

            // Dessert (Category 4)
            [
                'category_id' => 4,
                'name' => 'Es Pisang Ijo',
                'description' => 'Pisang dalam adonan hijau dengan es serut dan sirup merah',
                'price' => 25000,
                'image' => 'https://via.placeholder.com/400x300?text=Pisang+Ijo',
                'is_vegetarian' => true,
                'is_spicy' => false,
                'spicy_level' => null,
                'is_available' => true,
                'view_count' => rand(30, 120),
                'sort_order' => 1,
            ],
            [
                'category_id' => 4,
                'name' => 'Klepon',
                'description' => 'Kue tradisional berisi gula merah dengan taburan kelapa parut (5 pcs)',
                'price' => 15000,
                'image' => 'https://via.placeholder.com/400x300?text=Klepon',
                'is_vegetarian' => true,
                'is_spicy' => false,
                'spicy_level' => null,
                'is_available' => true,
                'view_count' => rand(30, 120),
                'sort_order' => 2,
            ],
            [
                'category_id' => 4,
                'name' => 'Kolak Pisang Ubi',
                'description' => 'Kolak hangat dengan pisang kepok, ubi, dan tape singkong',
                'price' => 22000,
                'image' => 'https://via.placeholder.com/400x300?text=Kolak',
                'is_vegetarian' => true,
                'is_spicy' => false,
                'spicy_level' => null,
                'is_available' => true,
                'view_count' => rand(30, 120),
                'sort_order' => 3,
            ],
            [
                'category_id' => 4,
                'name' => 'Puding Santan',
                'description' => 'Puding kenyal dengan kuah santan gula merah yang manis',
                'price' => 20000,
                'image' => 'https://via.placeholder.com/400x300?text=Puding+Santan',
                'is_vegetarian' => true,
                'is_spicy' => false,
                'spicy_level' => null,
                'is_available' => true,
                'view_count' => rand(30, 120),
                'sort_order' => 4,
            ],
            [
                'category_id' => 4,
                'name' => 'Martabak Manis Mini',
                'description' => 'Martabak manis mini dengan berbagai topping pilihan',
                'price' => 30000,
                'image' => 'https://via.placeholder.com/400x300?text=Martabak+Mini',
                'is_vegetarian' => true,
                'is_spicy' => false,
                'spicy_level' => null,
                'is_available' => true,
                'view_count' => rand(30, 120),
                'sort_order' => 5,
            ],
        ];

        foreach ($menus as $menu) {
            Menu::create($menu);
        }
    }
}
